[craftr]
linkModules = [ "vendor/craftr/net.maxon.c4d",
                "vendor/craftr/net.dlib" ]

[c4d]
rtti = true

[dlib]
nogui = true
isocpp = false
directory = "vendor/davisking/dlib"

[msvc]
version = 140
