[craftr]
linkModules = [ "vendor/craftr/net.maxon.c4d",
                "vendor/craftr/net.dlib" ]

[osx]
minversion = "10.11"  # El Capitan

[c4d]
rtti = true
release = "21.115"

[dlib]
nogui = true
isocpp = false
directory = "vendor/davisking/dlib"

[msvc]
#version = 140
version = 0
